name: "Build and Test"

on:
  push:
    branches: [ main ]

jobs:
  test-retry:
    uses: nick-fields/retry@v3
    with:
      timeout_minutes: 10
      max_attempts: 3
      command: | 
        echo "Hello, World!"
        exit 2
        echo "This line will not be executed"
        echo "This line will not be executed 2"
